board/urls.py
"""
the url routing for view sets of django rest framework, extended from django routing
"""
from rest_framework.routers import DefaultRouter

from . import views  # where the view sets are defined

router = DefaultRouter(trailing_slash=False)  # for consistency with backbone's url format
# register each view sets
router.register(r'sprints', views.SprintViewSet)
router.register(r'tasks', views.TaskViewSet)
router.register(r'users', views.UserViewSet)

scrum/urls.py
from django.conf.urls import url, include  # for including the url routing from django-rest-framework
from django.contrib import admin
from rest_framework.authtoken.views import obtain_auth_token

from board.urls import router  # django-rest routing

from django.views.generic import TemplateView  # generic page view

urlpatterns = [
    url(r'^api/token/', obtain_auth_token, name='api-token'),  # an API token getter
    url(r'^api/', include(router.urls)),  # django rest routing, API end points view sets
    url(r'^$', TemplateView.as_view(template_name='board/index.html')),  # for the single page template
    url(r'^admin/', admin.site.urls),  # just for debugging
]

board/models.py
from django.conf import settings  # for assign task to user
from django.utils.translation import ugettext_lazy as _  # lazy text getter

from django.db import models
from django.contrib.auth.models import User  # for customizing user model
from django.db.models.signals import post_save  # for Profile link
from django.dispatch import receiver  # for decorating User model functions


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    address_first = models.CharField(max_length=100, blank=True)
    address_second = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=40, blank=True)
    state = models.CharField(max_length=20, blank=True)
    zip = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=20, default='United States')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Sprint(models.Model):
    """Development iteration period."""

    name = models.CharField(max_length=100, blank=True, default='')
    description = models.TextField(blank=True, default='')
    end = models.DateField(unique=True)  # only one spring can be ended at one moment of time

    def __str__(self):
        return self.name or _('Sprint ending %s') % self.end  # to string


class Task(models.Model):
    """Unit of work to be done for the sprint."""

    # status code for task
    STATUS_TODO = 1
    STATUS_IN_PROGRESS = 2
    STATUS_TESTING = 3
    STATUS_DONE = 4

    # status text
    STATUS_CHOICES = (
        (STATUS_TODO, _('Not Started')),
        (STATUS_IN_PROGRESS, _('In Progress')),
        (STATUS_TESTING, _('Testing')),
        (STATUS_DONE, _('Done')),
    )

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, default='')
    sprint = models.ForeignKey(Sprint, blank=True, null=True)  # a Task belongs to a Sprint
    status = models.SmallIntegerField(choices=STATUS_CHOICES, default=STATUS_TODO)  # from status code/text
    order = models.SmallIntegerField(default=0)  # for sorting
    assigned = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)  # only auth user can be assigned task
    started = models.DateField(blank=True, null=True)
    due = models.DateField(blank=True, null=True)
    completed = models.DateField(blank=True, null=True)  # dates for start, due, completion

    def __str__(self):
        return self.name  # to string

board/views.py
from django.shortcuts import render

from rest_framework import authentication, permissions, viewsets, filters  # viewSets related libs for creating resource lists

from django.contrib.auth import get_user_model  # for a uniformed user model
from .models import Sprint, Task  # the Sprint model
from .serializers import SprintSerializer, TaskSerializer, UserSerializer  # the serializer

User = get_user_model()  # the uniformed user model


class DefaultsMixin(object):
    """Default settings for view authentication, permissions, filtering and pagination."""
    authentication_classes = (  # authentication from rest-framework
        authentication.BasicAuthentication,
        authentication.TokenAuthentication,
    )
    permission_classes = (
        permissions.IsAuthenticated,
    )
    paginate_by = 25
    paginate_by_param = 'page_size'
    max_paginate_by = 100
    filter_backends = (  # filters from rest-framework
        filters.DjangoFilterBackend,  # the base
        filters.SearchFilter,  # need a search field in viewsets
        filters.OrderingFilter,  # order field in viewsets
    )


class SprintViewSet(DefaultsMixin, viewsets.ModelViewSet):
    """API endpoint for listing and creating sprints."""
    queryset = Sprint.objects.order_by('end')  # sort by end date desc
    serializer_class = SprintSerializer  # appoint it's own serializer
    # filtering options
    search_fields = ('name', )  # allow search by these fields
    ordering_fields = ('end', 'name', )  # allow order by these fields


class TaskViewSet(DefaultsMixin, viewsets.ModelViewSet):
    """API endpoint for listing and creating tasks."""
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    # filtering options
    search_fields = ('name', 'description', )  # allow search by these fields
    ordering_fields = ('name', 'order', 'started', 'due', 'completed', )  # allow order by these fields


class UserViewSet(DefaultsMixin, viewsets.ModelViewSet):  # allow modification to user in the API endpoints
    """API endpoint for listing users."""
    lookup_field = User.USERNAME_FIELD  # search user by username instead of key id
    lookup_url_kwarg = User.USERNAME_FIELD  # for consistency
    queryset = User.objects.order_by(User.USERNAME_FIELD)
    serializer_class = UserSerializer
    # filtering options
    search_fields = (User.USERNAME_FIELD, )  # allow search by these fields

board/templates/board/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Scrum Board for HelloWorld Assessment</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="{% static 'board/vendor/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'board/css/board.css' %}">

  <script type="text/html" id="home-template">
    <h2>Your Sprints</h2>
    <button class="add" type="submit">Add Sprint</button>
    <% if (sprints !== null) { %>
    <div class="sprints">
      <% _.each(sprints.models, function (sprint) { %>
      <a href="#sprint/<%- sprint.get('id') %>" class="sprint">
        <%- sprint.get('name') %> <br>
        <span>DUE BY <%- sprint.get('end') %></span>
      </a>
      <% }); %>
    </div>
    <% } else { %>
    <h3 class="loading">Loading...</h3>
    <% } %>
  </script>

  <script type="text/html" id="header-template">
    <span class="title">Mini Scrum Board for HelloWorld Coding Assessment</span>
    <% if (authenticated) { %>
    <nav>
      <a href="/" class="button">Your Sprints</a>
      <a href="#" class="logout button">Logout</a>
    </nav>
    <% } %>
  </script>

  <script type="text/html" id="login-template">
    <form action="" method="post">
      <label for="id_username">Username</label>
      <input id="id_username" type="text" name="username"
             maxlength="30" required />
      <label for="id_password">Password</label>
      <input id="id_password" type="password"
             name="password" required />
      <button type="submit">Login</button>
    </form>
  </script>

  <script type="text/html" id="new-sprint-template">
    <form action="" method="post">
      <label for="id_name">Sprint Name</label>
      <input id="id_name" type="text" name="name" maxlength="100" required />
      <label for="id_end">End Date</label>
      <input id="id_end" type="date" name="end" />
      <label for="id_description">Description</label>
      <textarea id="id_description" name="description" cols="50"></textarea>
      <button class="cancel">Cancel</button>
      <button type="submit">Create</button>
    </form>
  </script>

  <script type="text/html" id="sprint-template">
    <% if (sprint !== null) { %>
    <% if (!sprint.invalid) { %>
    <h2><%- sprint.get('name') %></h2>
    <span class="due-date">Due <%- sprint.get('end') %></span>
    <p class="description"><%- sprint.get('description') %></p>
    <div class="tasks"></div>
    <% } else { %>
    <h1>Sprint <%- sprint.get('id') %> not found.</h1>
    <% } %>
    <% } else { %>
    <h1 class="loading">Loading...</h1>
    <% } %>
  </script>

</head>
<body>

  <div id="content"></div>

  <script src="{% static 'board/vendor/jquery.js' %}"></script>
  <script src="{% static 'board/vendor/underscore.js' %}"></script>
  <script src="{% static 'board/vendor/backbone.js' %}"></script>

  <script id="config" type="text/json">
    {
      "models": {},
      "collections": {},
      "views": {},
      "router": null,
      "apiRoot": "{% url 'api-root' %}",
      "apiLogin": "{% url 'api-token' %}"
    }
  </script>
  <script src="{% static 'board/js/app.js' %}"></script>
  <script src="{% static 'board/js/models.js' %}"></script>
  <script src="{% static 'board/js/views.js' %}"></script>
  <script src="{% static 'board/js/router.js' %}"></script>
</body>
</html>